import { useEffect, useState } from 'react';
import Head from "next/head";
import axios from 'axios';
import Header from './Header';
import { getToken } from '../../utils/auth';

function Layout({ children }) {
    const [name, setName] = useState('');
    const [image, setImage] = useState('');

    useEffect(() => {
        var token = getToken()

        try {
            axios.post(process.env.NEXT_PUBLIC_BACKEND_URL + "auth/profile", {
                token: token,
            }, {
                headers: {
                    'Content-Type': 'application/json',
                }
            }).then((response) => {
                setName(response.data.user?.name);
                setImage(response.data.user?.image);
            }).catch((error) => {
                console.error('An error occurred:', error);
            });

        } catch (error) {
            console.error('Error fetching data:', error.message);
        }
    }, []);

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <div
                    className="container-fluid bg-light"
                    style={{ backgroundColor: "#FFFFFF" }}
                >
                    <header style={{ backgroundColor: "#F7F9FF" }}>
                        <div className="header p-2" style={{ backgroundColor: "#F7F9FF" }}>
                            <nav
                                className="navbar bg-body-tertiary"
                                style={{ backgroundColor: "#F7F9FF" }}
                            >
                                <div className="container-fluid">
                                    <a className="navbar-brand" href="#">
                                        <img
                                            src="/designerr-logo.png"
                                            alt="Logo"
                                            width="72%"
                                            height="auto"
                                            className="d-inline-block align-text-top"
                                        />
                                    </a>
                                </div>
                            </nav>
                        </div>
                    </header>
                    {children}
                </div>
            </main> 
        </div>
    );
}

export default Layout;
