import React, { useEffect, useState } from 'react'
import Head from "next/head";
import Image from "next/image";
import { checkLogin, getToken } from '../utils/auth';
import { useRouter } from "next/router";
import UserInput from '../components/UserInput';
import AiInput from '../components/AiInput';
import axios from 'axios';

const chat = () => {

  const [chatInput, setChatInput] = useState('');
  const [newchat, setNewChat] = useState(false);
  const [appendedComponents, setAppendedComponents] = useState([]);

  const router = useRouter();

  useEffect(() => {
    if (!checkLogin()) {
      router.push('/signin');
    }
  }, [])

  const handleChatInputChange = (e) => {
    setChatInput(e.target.value);
  };

  const submitQuestion = async () => {
    // Update the chat input state
    const userMessage = <UserInput message={'User: ' + chatInput} />;
    setAppendedComponents(prevComponents => [...prevComponents, userMessage]);

    // Update the appended components state
    const aiMessage = <AiInput message="AI: Noted on that... Please wait in a bit, Thanks!" />
    setAppendedComponents(prevComponents => [...prevComponents, aiMessage]);

    var token = getToken()  

    try {
      const response = await fetch(process.env.NEXT_PUBLIC_PYTHON_SERVER_URL + "generate_image_with_prompt", {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ prompt: chatInput }), // Convert the object to a JSON string
      });

      if (response.ok) {
        const responseData = await response.json();

        if (responseData && responseData.image_url) {

          // console.log(responseData.image_url);
          // Store img in s3
          // const response2 = await fetch(process.env.NEXT_PUBLIC_BACKEND_URL + "chat/upload_img", {
          //   method: 'POST',
          //   headers: {
          //     'Content-Type': 'application/json',
          //   },
          //   body: JSON.stringify({
          //     imageUrl: process.env.NEXT_PUBLIC_PYTHON_SERVER_URL + responseData.image_url
          //   }), // Convert the object to a JSON string
          // });

          

          const response3 = await fetch(process.env.NEXT_PUBLIC_BACKEND_URL + "chat/save_chat", {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              token: token,
              prompt: chatInput,
              imageUrl: process.env.NEXT_PUBLIC_PYTHON_SERVER_URL + responseData.image_url
            }), // Convert the object to a JSON string
          });


          const aiMessagewithImg = <AiInput message="AI: Thank you for waiting! Kindly see the results below:"
            image={process.env.NEXT_PUBLIC_PYTHON_SERVER_URL + responseData.image_url}
          />
          setAppendedComponents(prevComponents => [...prevComponents, aiMessagewithImg]);
        }
      } else {
        setError('Network request failed.');
      }

    } catch (error) {
      console.error('Error:', error);
      // Handle error
    }
    setChatInput('');
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className="container-fluid bg-light"
        style={{ backgroundColor: "#FFFFFF" }}
      >
        <header style={{ backgroundColor: "#F7F9FF" }}>
          <div className="header p-2" style={{ backgroundColor: "#F7F9FF" }}>
            <nav className="navbar navbar-expand-lg navbar-light bg-light">
              <div className="container-fluid">
                <a className="navbar-brand" href="#">
                  <img
                    src="/designerr-logo.png"
                    alt="Logo"
                    width="72%"
                    height="auto"
                    className="d-inline-block align-text-top"
                  />
                </a>

                <div
                  className="collapse navbar-collapse d-flex justify-content-end"
                  id="navbarSupportedContent"
                >
                  <div className="d-flex justify-content-end">
                    <img
                      src="/user-img1.png"
                      alt="Logo"
                      width="72%"
                      height="auto"
                      className="d-inline-block align-text-top"
                    />
                    <p style={{ fontSize: 16 }}>John Doe</p>
                  </div>
                </div>
              </div>
            </nav>
          </div>
        </header>

        <div className="row">
          <div className="container max814-2">
            <div className="row">
              {/* <div
                className="col-3"
                style={{
                  backgroundColor: "#fff",
                  color: "#000",
                  height: "850px",
                }}
              >
                <div style={{ backgroundColor: "transparent" }}>
                  <div className="m-3">
                    <button className="new-chat" id="sidebarNewChat_btn" onClick={() => setNewChat(true)}>
                      + New Chat
                    </button>
                  </div>

                  <div className="mt-4">
                    <p className="tyni-heading1 mx-3 ">Today</p>
                    <ul className="text-start">
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                    </ul>
                  </div>

                  <div className="mt-4">
                    <p className="tyni-heading1 mx-3 ">Yesterday</p>
                    <ul className="text-start">
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                    </ul>
                  </div>

                  <div className="mt-4">
                    <p className="tyni-heading1 mx-3 ">Previous 7 Days</p>
                    <ul className="text-start">
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                      <li>
                        {" "}
                        <span className="custom-li-style"></span> Lorem Ipsum
                        Sit Dolor...{" "}
                      </li>
                    </ul>
                  </div>
                </div>
              </div> */}
              <div
                className="col-12"
                style={{ backgroundColor: "#F2F5FF", color: "#000" }}
              >
                <div>
                  {appendedComponents.map((component, index) => (
                    <div key={index}>{component}</div>
                  ))}

                  {/* <UserInput message="User: Create a Landing page about Backend Engineering with
                this website references www.designer.com"/>

                  <AiInput message="AI: Noted on that... Please wait in a bit, Thanks!" />

                  <AiInput
                    message="AI: Thank you for waiting! Kindly see the results below:"
                    image="/../public/Frame 1000003921.png"
                  /> */}

                </div>

                <div className="row " style={{ height: 200 }}>
                  <div
                    className="row d-flex justify-content-center bottom-input-set"
                    style={{ backgroundColor: "#fff" }}
                  >
                    <div
                      // className="p-2"
                      style={{ backgroundColor: "transparent", height: 40 }}
                      id="input-container"
                    >
                      {/* <div
                    className="input-group mb-3 bg-transparent"
                    className="input-wrapper"
                  > */}
                      <input
                        style={{ height: 60 }}
                        type="text"
                        id="user-input"
                        value={chatInput}
                        onChange={handleChatInputChange}
                        placeholder="Type your message..."
                      />

                      <button id="send-button" style={{ height: 60 }} onClick={submitQuestion}>
                        {/* <span
                        className="input-group-text bg-transparent"
                        id="basic-addon2"
                      > */}
                        <Image
                          src="/Group 1000003745.png"
                          alt="My Image"
                          width={25}
                          height={25}
                          className="me-2 cment_nofill"
                        />
                        {/* </span> */}
                      </button>
                    </div>
                    {/* </div> */}
                  </div>
                </div>

                {/* bottom-input-field */}
              </div>
            </div>

            {/*------------------------------------------------  */}

            {/* <div className="row ">
            <div
              className="col-9 pt-5"
              style={{ backgroundColor: "#494659" }}
              id="bottom-right-side"
            >
              <div
                style={{ backgroundColor: "#A4AAB6" }}
                id="input-container"
              >
                <div
                  className="input-group mb-3 bg-transparent"
                  className="input-wrapper"
                >
                  <input
                    type="text"
                    id="user-input"
                    placeholder="Type your message..."
                  />

                  <button id="send-button">
                    <span
                      className="input-group-text bg-transparent"
                      id="basic-addon2"
                    >
                      <Image
                        src="/images/icons/Frame 1000003894.png"
                        alt="My Image"
                        width={16}
                        height={10}
                        className="me-2 cment_nofill"
                      />
                    </span>
                  </button>
                </div>
              </div>
            </div>
          </div> */}
          </div>
        </div>
      </div>
    </div>
  )
}

export default chat