import React from 'react'
import Head from "next/head";
import Image from "next/image";

const chat2 = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div
                className="container-fluid bg-light"
                style={{ backgroundColor: "#FFFFFF" }}
            >
                <header style={{ backgroundColor: "#F7F9FF" }}>
                    <div className="header p-2" style={{ backgroundColor: "#F7F9FF" }}>
                        <nav className="navbar navbar-expand-lg navbar-light bg-light">
                            <div className="container-fluid">
                                <a className="navbar-brand" href="#">
                                    <img
                                        src="/designerr-logo.png"
                                        alt="Logo"
                                        width="72%"
                                        height="auto"
                                        className="d-inline-block align-text-top"
                                    />
                                </a>

                                <div
                                    className="collapse navbar-collapse d-flex justify-content-end"
                                    id="navbarSupportedContent"
                                >
                                    <div className="d-flex justify-content-end">
                                        <img
                                            src="/user-img1.png"
                                            alt="Logo"
                                            width="72%"
                                            height="auto"
                                            className="d-inline-block align-text-top"
                                        />
                                        <p style={{ fontSize: 16 }}>John Doe</p>
                                    </div>
                                </div>
                            </div>
                        </nav>
                    </div>
                </header>

                <div>
                    <div className="row" style={{ height: "calc(100vh - 100px)" }}>
                        <div className="col-md-3 bg-white" style={{ height: "calc(100vh - 100px)", overflow: "scroll" }}>
                            <button className="new-chat mt-3" id="sidebarNewChat_btn">
                                + New Chat
                            </button>

                            <div className="mt-4">
                                <p className="tyni-heading1 mx-3 ">Today</p>
                                <ul className="text-start">
                                    <li>
                                        <span className="custom-li-style"></span> Lorem Ipsum
                                        Sit Dolor...
                                    </li>
                                    <li>
                                        <span className="custom-li-style"></span> Lorem Ipsum
                                        Sit Dolor...
                                    </li>
                                    <li>

                                        <span className="custom-li-style"></span> Lorem Ipsum
                                        Sit Dolor...
                                    </li>
                                    <li>

                                        <span className="custom-li-style"></span> Lorem Ipsum
                                        Sit Dolor...
                                    </li>
                                </ul>
                            </div>

                            <div className="mt-4">
                                <p className="tyni-heading1 mx-3 ">Yesterday</p>
                                <ul className="text-start">
                                    <li>

                                        <span className="custom-li-style"></span> Lorem Ipsum
                                        Sit Dolor...
                                    </li>
                                    <li>

                                        <span className="custom-li-style"></span> Lorem Ipsum
                                        Sit Dolor...
                                    </li>
                                    <li>

                                        <span className="custom-li-style"></span> Lorem Ipsum
                                        Sit Dolor...
                                    </li>
                                    <li>

                                        <span className="custom-li-style"></span> Lorem Ipsum
                                        Sit Dolor...
                                    </li>
                                </ul>
                            </div>

                            <div className="mt-4">
                                <p className="tyni-heading1 mx-3 ">Previous 7 Days</p>
                                <ul className="text-start">
                                    <li>

                                        <span className="custom-li-style"></span> Lorem Ipsum
                                        Sit Dolor...
                                    </li>
                                    <li>

                                        <span className="custom-li-style"></span> Lorem Ipsum
                                        Sit Dolor...
                                    </li>
                                    <li>

                                        <span className="custom-li-style"></span> Lorem Ipsum
                                        Sit Dolor...
                                    </li>
                                    <li>

                                        <span className="custom-li-style"></span> Lorem Ipsum
                                        Sit Dolor...
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <div className="col-md-9" style={{ height: "calc(100vh - 100px)", background: "#F8F9FA" }}>
                            <div className='bg-white right_alignments'>
                                <p>add</p>
                            </div>
                            <div className='bg-white right_alignments w-100 position-absolute bottom-0 pb-5'>
                                <div>
                                    <input
                                        style={{ height: 60 }}
                                        type="text"
                                        id="user-input"
                                        value={'ddd'}
                                        placeholder="Type your message..."
                                    />

                                    <button id="send-button" style={{ height: 60 }}>
                                        <Image
                                            src="/Group 1000003745.png"
                                            alt="My Image"
                                            width={25}
                                            height={25}
                                            className="me-2 cment_nofill"
                                        />
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}

export default chat2