import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container" style={{ backgroundColor: "#F7F9FF" }}>
          <div className="header p-2" style={{ backgroundColor: "#F7F9FF" }}>
            {/* <nav className="navbar bg-body-tertiary">
              <div className="container-fluid">
                <a className="navbar-brand" href="#">
                  <img
                    src="/designerr-logo.png"
                    alt="Logo"
                    width="72%"
                    height="auto"
                    class="d-inline-block align-text-top"
                  />
                </a>
              </div>
            </nav> */}
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
              <div className="container-fluid">
                <a className="navbar-brand" href="#">
                  <img
                    src="/designerr-logo.png"
                    alt="Logo"
                    width="72%"
                    height="auto"
                    class="d-inline-block align-text-top"
                  />
                </a>

                <div
                  className="collapse navbar-collapse d-flex justify-content-end"
                  id="navbarSupportedContent"
                >
                  <div className="d-flex justify-content-end">
                    <img
                      src="/user-img1.png"
                      alt="Logo"
                      width="72%"
                      height="auto"
                      class="d-inline-block align-text-top"
                    />
                    <p>John Doe</p>
                  </div>
                </div>
              </div>
            </nav>
          </div>

          <div className="body-content d-flex justify-content-center mt-6 ">
            <div
              className="card shadow p-3 mb-5 bg-body-tertiary rounded"
              style={{ width: "25rem" }}
            >
              <div className="card-body">
                <h5 className="card-title text-center">Sign In</h5>

                <div className="mb-3">
                  <label for="exampleFormControlInput1" className="form-label">
                    Name
                  </label>
                  <input
                    type="email"
                    className="form-control"
                    id="exampleFormControlInput1"
                    placeholder="Enter your username"
                  />
                </div>

                <div className="mb-3">
                  <label for="exampleFormControlInput1" className="form-label">
                    Email address
                  </label>
                  <input
                    type="email"
                    className="form-control"
                    id="exampleFormControlInput1"
                    placeholder="Enter your email address"
                  />
                </div>
                <div className="mb-3">
                  <div className="row d-flex  ">
                    <button
                      type="button"
                      className="btn btn-primary "
                      width="200%"
                    >
                      Sign in with Email
                    </button>
                  </div>
                </div>

                <div className="mb-3">
                  <div className="row d-flex  ">
                    <button
                      type="button"
                      className="btn btn-outline-dark "
                      width="100%"
                    >
                      <span>
                        <img
                          className="img-thumbnail"
                          src="/Google logo.svg"
                        ></img>
                      </span>
                      Sign in with Google
                    </button>
                  </div>
                </div>

                <div className="mb-3">
                  <div className="row d-flex  ">
                    <button
                      type="button"
                      className="btn btn-outline-dark "
                      width="100%"
                    >
                      <span>
                        <img className="img-thumbnail" src="/fb-logo.svg"></img>
                      </span>
                      Sign in with Facebook
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
