import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
// import styles from "../styles/Home.module.css";
import { checkLogin } from '../utils/auth';
import { useRouter } from "next/router";
import CheckoutForm from "../components/CheckoutForm";

import { loadStripe } from "@stripe/stripe-js";
import { Elements } from "@stripe/react-stripe-js";

const stripePromise = loadStripe(process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY);

export default function Payment() {

  const [clientSecret, setClientSecret] = useState('');

  useEffect(() => {
    // Create PaymentIntent as soon as the page loads
    fetch("/api/create-payment-intent", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ items: [{ id: "xl-tshirt" }] }),
    })
      .then((res) => res.json())
      .then((data) => setClientSecret(data.clientSecret));
  }, []);

  const appearance = {
    theme: 'stripe',
  };
  const options = {
    clientSecret,
    appearance,
  };

  const router = useRouter();

  useEffect(() => {
    if (!checkLogin()) {
      router.push('/signin');
    }
  }, [])

  return (
    <div>
      <Head>
        <title>Designerr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container-fluid" style={{ backgroundColor: "#F7F9FF" }}>
        <header>
          <div className="header p-2" style={{ backgroundColor: "#F7F9FF" }}>
            <nav className="navbar bg-body-tertiary">
              <div className="container-fluid">
                <a className="navbar-brand" href="#">
                  <img
                    src="/designerr-logo.png"
                    alt="Logo"
                    width="72%"
                    height="auto"
                    className="d-inline-block align-text-top"
                  />
                </a>
              </div>
            </nav>
          </div>
        </header>
        <div className="row">
          <h1 className="text-center text-primary text-uppercase fw-bold mb-5">
            Enter Your Payment Details Below
          </h1>
        </div>



        <div
          className="row d-flex justify-content-center mt-6 "
          style={{ backgroundColor: "transparent" }}
        >

          <div className="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-xs-12 bg   ">
            <div>
              <div
                className="card mb-2 p-4 shadow p-3 mb-5 bg-white rounded "
              >
                <div className="card.content">
                  <h4 className="mb-5">Payment Information</h4>
                  {clientSecret && (
                    <Elements options={options} stripe={stripePromise}>
                      <CheckoutForm />
                    </Elements>
                  )}
                  {/* <div className="form">
                        <div className="form-group">
                          <label htmlFor="formGroupExampleInput">
                            <h6>Name *</h6>
                          </label>
                          <input
                            type="text"
                            className="form-control shadow-none p-2 mb-4 bg-light rounded "
                            id="formGroupExampleInput"
                            placeholder="Enter your full name"
                          />
                        </div>

                        <div className="form-group">
                          <label htmlFor="exampleInputEmail1">
                            <h6>Email *</h6>
                          </label>
                          <input
                            type="email"
                            className="form-control shadow-none p-2 mb-4 bg-light rounded "
                            id="exampleInputEmail1"
                            aria-describedby="emailHelp"
                            placeholder="Enter your email address"
                          />
                        </div>


                        <div className="form-group">
                          <label htmlFor="examplecardNumber">
                            <h6>Card Details *</h6>
                          </label>
                          <div className="input-group  shadow-none p-2 mb-4 bg-light rounded border">
                            <div className="input-group-append">
                              <span className="input-group-text shadow-none bg-light rounded">
                                
                              </span>
                            </div>
                            <input
                              type="text"
                              className="form-control border-0 px-1 shadow-none  bg-light rounded"
                              id="formGroupExampleInput-no"
                              placeholder="0000 0000 0000 000"
                            />
                            <input
                              type="text"
                              className="form-control  border-0 px-1 align-right shadow-none  bg-light rounded"
                              id="formGroupExampleInput-date"
                              placeholder="MM /YY"
                            />
                            <input
                              type="text"
                              className="form-control border-0 px-1 shadow-none  bg-light rounded"
                              id="formGroupExampleInput-cvv"
                              placeholder="CVV"
                            />
                            <input
                              type="text"
                              className="form-control border-0 px-1 shadow-none  bg-light rounded"
                              id="formGroupExampleInput-zip"
                              placeholder="ZIP Code"
                            />
                          </div>
                        </div>


                        <button
                          type="button"
                          className="btn btn-primary "
                          width="200%"
                          style={{
                            borderRadius: 30,
                          }}
                        >
                          Submit
                        </button>
                      </div> */}
                </div>
              </div>
            </div>
          </div>

          <div className="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-xs-12  ">
            <div
              className="card mb-2 p-4 shadow p-3 mb-5 bg-white rounded "
            // style={{ top: -200 }}
            >
              <div className="card.content">
                <h4 className=" text-left  mb-2 text-muted">
                  You have to pay
                </h4>
                <h1> $99/mo</h1>

                <hr />

                <h6 className="font-weight-bold">What’s included</h6>

                <ul
                  style={{
                    listStyleType: "disc",
                    margin: 0,
                    paddingLeft: 18,
                    color: "#2F70A6",
                  }}
                >
                  <li>
                    <span style={{ color: "black" }}>
                      Eget nunc scelerisque viverra
                    </span>
                  </li>
                  <li>
                    <span style={{ color: "black" }}>
                      Mauris in aliquam
                    </span>
                  </li>
                  <li>
                    <span style={{ color: "black" }}>
                      Nunc faucibus a pellentesque sit
                    </span>
                  </li>
                  <li>
                    <span style={{ color: "black" }}>
                      Ut sem viverra aliquet
                    </span>
                  </li>
                  <li>
                    <span style={{ color: "black" }}>
                      Pretium vulputate sapien
                    </span>
                  </li>
                </ul>
              </div>
            </div>
          </div>



          {/* <div className="row" style={{ backgroundColor: "pink" }}>
            <div className="col-12 col-md-7 col-lg-7">
              <div className="card shadow p-3 mb-5 bg-body-tertiary rounded">
                <div className="card-body">
                  <h5 className="card-title text-left">Payment Information</h5>

                  <div className="mb-3">
                    <label
                      for="exampleFormControlInput1"
                      className="form-label"
                    >
                      Name *
                    </label>
                    <input
                      type="email"
                      className="form-control"
                      id="exampleFormControlInput1"
                      placeholder="Enter your username"
                    />
                  </div>

                  <div className="mb-3">
                    <label
                      for="exampleFormControlInput1"
                      className="form-label"
                    >
                      Email address *
                    </label>
                    <input
                      type="email"
                      className="form-control"
                      id="exampleFormControlInput1"
                      placeholder="Enter your email address"
                    />
                  </div>

                  <div className="mb-3">
                    <label
                      for="exampleFormControlInput1"
                      className="form-label"
                    >
                      Card Details *
                    </label>
                    <input
                      type="number"
                      className="form-control"
                      id="exampleFormControlInput1"
                      placeholder="0000 0000 0000 0000"
                    />
                  </div>
                  <div className="mb-3">
                    <div className="row d-flex  ">
                      <button
                        type="button"
                        className="btn btn-primary "
                        width="200%"
                      >
                        submit
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div
              className="col-12 col-md-5 col-lg-5"
              style={{ backgroundColor: "yellow" }}
            >
              <div
                className="card  shadow bg-body-tertiary rounded"
                style={{ maxWidth: 300 }}
              >
                <div className="card-body">
                  <p className="card-subtitle  text-left text-primary">
                    You have to pay
                  </p>
                  <h1 className="card-title text-left  mb-2 text-muted">
                    $99/mo
                  </h1>
                  <hr></hr>
                  <h6 className="card-text text-left ">What’s included</h6>

                  <ul>
                    <li>Eget nunc scelerisque viverra</li>
                    <li>Mauris in aliquam</li>
                    <li>Nunc faucibus a pellentesque sit</li>
                    <li>Ut sem viverra aliquet</li>
                    <li>Pretium vulputate sapien</li>
                  </ul>
                </div>
              </div>
            </div>
          </div> */}
        </div>
      </div>


    </div>
  );
}
