import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
// import styles from "../styles/Home.module.css";
import { checkLogin, getToken } from '../utils/auth';
import { useRouter } from "next/router";
import CheckoutForm from "../components/CheckoutForm";

import { loadStripe } from "@stripe/stripe-js";
import { Elements } from "@stripe/react-stripe-js";
import Layout from "../components/logged/Layout";

const stripePromise = loadStripe(process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY);

export default function Payment() {

  const [clientSecret, setClientSecret] = useState('');

  useEffect(() => {
    if (!checkLogin()) {
      router.push('/signin');
    }
  }, [])

  useEffect(() => {
    fetch(process.env.NEXT_PUBLIC_BACKEND_URL + "payment/create-payment-intent", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        items: [{ id: "xl-tshirt" }],
        token: getToken()
      }),
    })
      .then((res) => res.json())
      .then((data) => setClientSecret(data.clientSecret));
  }, []);

  const appearance = {
    theme: 'stripe',
  };
  const options = {
    clientSecret,
    appearance,
  };

  const router = useRouter();



  return (
    <div>
      <Layout>
        <div className="row">
          <h1 className="text-center text-primary text-uppercase fw-bold mb-5 mt-3">
            Enter Your Payment Details Below
          </h1>
        </div>



        <div
          className="row d-flex justify-content-center mt-6 "
          style={{ backgroundColor: "transparent" }}
        >

          <div className="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-xs-12 bg   ">
            <div>
              <div
                className="card mb-2 p-4 shadow p-3 mb-5 bg-white rounded "
              >
                <div className="card.content">
                  <h4 className="mb-5">Payment Information</h4>
                  {clientSecret && (
                    <Elements options={options} stripe={stripePromise}>
                      <CheckoutForm />
                    </Elements>
                  )}
                </div>
              </div>
            </div>
          </div>

          <div className="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-xs-12  ">
            <div
              className="card mb-2 p-4 shadow p-3 mb-5 bg-white rounded "
            // style={{ top: -200 }}
            >
              <div className="card.content">
                <h4 className=" text-left  mb-2 text-muted">
                  You have to pay
                </h4>
                <h1> $99/mo</h1>

                <hr />

                <h6 className="font-weight-bold">What’s included</h6>

                <ul
                  style={{
                    listStyleType: "disc",
                    margin: 0,
                    paddingLeft: 18,
                    color: "#2F70A6",
                  }}
                >
                  <li>
                    <span style={{ color: "black" }}>
                      Eget nunc scelerisque viverra
                    </span>
                  </li>
                  <li>
                    <span style={{ color: "black" }}>
                      Mauris in aliquam
                    </span>
                  </li>
                  <li>
                    <span style={{ color: "black" }}>
                      Nunc faucibus a pellentesque sit
                    </span>
                  </li>
                  <li>
                    <span style={{ color: "black" }}>
                      Ut sem viverra aliquet
                    </span>
                  </li>
                  <li>
                    <span style={{ color: "black" }}>
                      Pretium vulputate sapien
                    </span>
                  </li>
                </ul>
              </div>
            </div>
          </div>

        </div>
      </Layout>
      {/* <Head>
        <title>Designerr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container-fluid" style={{ backgroundColor: "#F7F9FF" }}>
        <header>
          <div className="header p-2" style={{ backgroundColor: "#F7F9FF" }}>
            <nav className="navbar bg-body-tertiary">
              <div className="container-fluid">
                <a className="navbar-brand" href="#">
                  <img
                    src="/designerr-logo.png"
                    alt="Logo"
                    width="72%"
                    height="auto"
                    className="d-inline-block align-text-top"
                  />
                </a>
              </div>
            </nav>
          </div>
        </header>
        <div className="row">
          <h1 className="text-center text-primary text-uppercase fw-bold mb-5">
            Enter Your Payment Details Below
          </h1>
        </div>



        <div
          className="row d-flex justify-content-center mt-6 "
          style={{ backgroundColor: "transparent" }}
        >

          <div className="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-xs-12 bg   ">
            <div>
              <div
                className="card mb-2 p-4 shadow p-3 mb-5 bg-white rounded "
              >
                <div className="card.content">
                  <h4 className="mb-5">Payment Information</h4>
                  {clientSecret && (
                    <Elements options={options} stripe={stripePromise}>
                      <CheckoutForm />
                    </Elements>
                  )}
                </div>
              </div>
            </div>
          </div>

          <div className="col-xl-4 col-lg-4 col-md-12 col-sm-12 col-xs-12  ">
            <div
              className="card mb-2 p-4 shadow p-3 mb-5 bg-white rounded "
            // style={{ top: -200 }}
            >
              <div className="card.content">
                <h4 className=" text-left  mb-2 text-muted">
                  You have to pay
                </h4>
                <h1> $99/mo</h1>

                <hr />

                <h6 className="font-weight-bold">What’s included</h6>

                <ul
                  style={{
                    listStyleType: "disc",
                    margin: 0,
                    paddingLeft: 18,
                    color: "#2F70A6",
                  }}
                >
                  <li>
                    <span style={{ color: "black" }}>
                      Eget nunc scelerisque viverra
                    </span>
                  </li>
                  <li>
                    <span style={{ color: "black" }}>
                      Mauris in aliquam
                    </span>
                  </li>
                  <li>
                    <span style={{ color: "black" }}>
                      Nunc faucibus a pellentesque sit
                    </span>
                  </li>
                  <li>
                    <span style={{ color: "black" }}>
                      Ut sem viverra aliquet
                    </span>
                  </li>
                  <li>
                    <span style={{ color: "black" }}>
                      Pretium vulputate sapien
                    </span>
                  </li>
                </ul>
              </div>
            </div>
          </div>

        </div>
      </div> */}


    </div>
  );
}
