import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { signIn } from "next-auth/react"
import { useState } from "react";



export default function Home({ providers }) {

  const [username, setUsername] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const handleSignIn = async () => {
    await signIn('google');
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    // Call the login API with username and password
    const response = await fetch('/api/login', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ username, password }),
    });

    if (response.ok) {
      // Redirect to the dashboard or perform other actions
      // e.g., set authentication state, save token, etc.
      console.log('Login successful');
    } else {
      console.log('Login failed');
    }
  };


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div
          className="container-fluid bg-light"
          style={{ backgroundColor: "#FFFFFF" }}
        >
          <header style={{ backgroundColor: "#F7F9FF" }}>
            <div className="header p-2" style={{ backgroundColor: "#F7F9FF" }}>

              <nav className="navbar navbar-expand-lg navbar-light bg-light">
                <div className="container-fluid">
                  <a className="navbar-brand" href="#">
                    <img
                      src="/designerr-logo.png"
                      alt="Logo"
                      width="72%"
                      height="auto"
                      className="d-inline-block align-text-top"
                    />
                  </a>

                  <div
                    className="collapse navbar-collapse d-flex justify-content-end"
                    id="navbarSupportedContent"
                  >
                    <div className="d-flex justify-content-end">
                      <img
                        src="/user-img1.png"
                        alt="Logo"
                        width="72%"
                        height="auto"
                        className="d-inline-block align-text-top"
                      />
                      <p style={{ fontSize: 16 }}>John Doe</p>
                    </div>
                  </div>
                </div>
              </nav>
            </div>
          </header>
          <div
            className="body-content d-flex justify-content-center mt-5 bg-light"
            style={{ backgroundColor: "#FFF" }}
          >
            <div
              className="card shadow p-3 mb-5 rounded"
              style={{ maxWidth: 730, backgroundColor: "#FFF" }}
            >
              <div className="card-body">
                <h2 className="card-title text-center text-uppercase fw-bold">
                  Sign In
                </h2>

                <div className="mb-3">
                  <label
                    htmlFor="exampleFormControlInput1"
                    className="form-label fw-bold"
                  >
                    Name
                  </label>
                  <input
                    type="name"
                    className="form-control"
                    id="exampleFormControlInput1"
                    placeholder="Enter your username"
                    width="100%"
                    height="85%"
                  />
                </div>

                <div className="mb-3">
                  <label
                    htmlFor="exampleFormControlInput1"
                    className="form-label fw-bold"
                  >
                    Email
                  </label>
                  <input
                    type="email"
                    className="form-control"
                    id="exampleFormControlInput1"
                    placeholder="Enter your email address"
                    width="100%"
                  />
                </div>

                <button
                  type="button"
                  className="btn btn-primary text-uppercase w-100 mb-4 mt-3 fw-bold"
                >
                  Sign in with Email
                </button>


                <button
                  type="button"
                  className="btn btn-outline-dark w-100 mb-4 fw-bold"
                  width="100%"
                  onClick={handleSignIn}
                >
                  <span>
                    <img
                      className="img-thumbnail bg-transparent border-0"
                      src="/Google logo.svg"
                    ></img>
                  </span>
                  Sign in with Google
                </button>


                <button
                  type="button"
                  className="btn btn-outline-dark w-100 mb-4 fw-bold"
                  width="100%"
                >
                  <span>
                    <img
                      className="img-thumbnail bg-transparent border-0"
                      src="/fb-logo.svg"
                    ></img>
                  </span>
                  Sign in with Facebook
                </button>


                <div className="mb-3">
                  <p className="text-center">
                    By continuing your agree to our privacy policy and terms and
                    conditions.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}


