import Head from 'next/head'
import React from 'react'
import Link from 'next/link'
import { logout } from '../../utils/auth';
import { useRouter } from "next/router";


const Header = ({ name, image }) => {

    const router = useRouter();

    const logoutClk = () =>{
        logout();
        router.push('/signin');
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header style={{ backgroundColor: "#F7F9FF" }}>
                <div className="header p-2" style={{ backgroundColor: "#F7F9FF" }}>
                    <nav className="navbar navbar-expand-lg navbar-light bg-light">
                        <div className="container-fluid">

                            <Link className="navbar-brand" href="/">
                                <img
                                    src="/designerr-logo.png"
                                    alt="Logo"
                                    width="72%"
                                    height="auto"
                                    className="d-inline-block align-text-top"
                                />
                            </Link>

                            <div
                                className="collapse navbar-collapse d-flex justify-content-end"
                                id="navbarSupportedContent"
                            >
                                <div className="d-flex justify-content-end">
                                    <div className="dropdown me-2">
                                        <div className="btn d-flex justify-content-end" data-bs-toggle="dropdown">
                                            <img
                                                src={image || "images/avatar.png"}
                                                alt="Logo"
                                                width="50"
                                                height="50"
                                                className="d-inline-block align-text-top rounded-circle"
                                            />
                                            <p style={{ fontSize: 16, fontWeight: 'bold', height: 40, lineHeight: '50px', marginLeft: 10 }}>
                                                {name}
                                            </p>
                                        </div>
                                        <ul className="dropdown-menu">
                                            <li>
                                                <a className="dropdown-item" onClick={logoutClk} href="#">Log Out</a>
                                            </li>
                                            <li>
                                                <Link className="dropdown-item" href="/profile">Profile</Link>
                                            </li>
                                        </ul>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </nav>
                </div>
            </header>
        </>
    )
}

export default Header